#!/usr/bin/env bash
#
# Find a USB/serial Unihedron SQM and generate a Docker Compose device mapping.

set -uo pipefail

GENERATED_MARKER="# Generated by setup-usb.sh"
OUTPUT_FILE="compose.override.yaml"
COMPOSE_FILE="compose.yaml"
REQUESTED_DEVICE=""
SKIP_PROBE=false
FORCE=false
ASSUME_YES=false
TEMPORARY_FILE=""

usage() {
  cat <<'EOF'
Usage: ./setup-usb.sh [options]

Find a USB/serial Unihedron SQM and generate a Compose device mapping.

Options:
  --device PATH          Probe this device instead of scanning the host
  --output FILE          File to generate (default: compose.override.yaml)
  --compose-file FILE    Base Compose file (default: compose.yaml)
  --skip-probe           Select without sending the read-only "ix" command
  --force                Replace an existing output file
  --yes                  Accept the only candidate without prompting
  -h, --help             Show this help
EOF
}

fail() {
  printf 'USB setup failed: %s\n' "$*" >&2
  exit 2
}

cleanup() {
  if [[ -n "$TEMPORARY_FILE" && -e "$TEMPORARY_FILE" ]]; then
    rm -f -- "$TEMPORARY_FILE"
  fi
}
trap cleanup EXIT

ask_yes_no() {
  local question=$1
  local default=$2
  local suffix answer
  if [[ "$default" == "yes" ]]; then
    suffix=' [Y/n] '
  else
    suffix=' [y/N] '
  fi
  while true; do
    read -r -p "${question}${suffix}" answer
    answer=${answer,,}
    if [[ -z "$answer" ]]; then
      [[ "$default" == "yes" ]]
      return
    fi
    case "$answer" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) printf 'Please enter y or n.\n' ;;
    esac
  done
}

validate_device() {
  local path=$1
  [[ "$path" == /dev/* ]] || return 1
  [[ "$path" != *$'\n'* && "$path" != *$'\r'* && "$path" != *"'"* ]] || return 1
  [[ -c "$path" ]]
}

describe_device() {
  local path=$1
  local target properties vendor model serial_number identity=""
  target=$(readlink -f -- "$path" 2>/dev/null || printf '%s' "$path")
  if command -v udevadm >/dev/null 2>&1; then
    properties=$(udevadm info --query=property --name="$path" 2>/dev/null || true)
    vendor=$(sed -n 's/^ID_VENDOR_FROM_DATABASE=//p; s/^ID_VENDOR=//p' <<<"$properties" | head -n1)
    model=$(sed -n 's/^ID_MODEL_FROM_DATABASE=//p; s/^ID_MODEL=//p' <<<"$properties" | head -n1)
    serial_number=$(sed -n 's/^ID_SERIAL_SHORT=//p' <<<"$properties" | head -n1)
    for value in "$vendor" "$model" "$serial_number"; do
      if [[ -n "$value" ]]; then
        [[ -n "$identity" ]] && identity+=" · "
        identity+="$value"
      fi
    done
  fi
  printf '%s → %s' "$path" "$target"
  [[ -n "$identity" ]] && printf ' · %s' "$identity"
}

PROBE_VERIFIED=false
PROBE_DETAIL=""

probe_device() {
  local path=$1
  local saved_settings fd response="" protocol model feature serial_number
  PROBE_VERIFIED=false
  PROBE_DETAIL=""

  if [[ "$SKIP_PROBE" == true ]]; then
    PROBE_DETAIL="probe skipped"
    return
  fi

  saved_settings=$(stty -g -F "$path" 2>/dev/null) || {
    PROBE_DETAIL="cannot read serial settings (check device permissions)"
    return
  }
  stty -F "$path" 115200 raw -echo cs8 -cstopb -parenb -ixon -ixoff -crtscts 2>/dev/null || {
    PROBE_DETAIL="cannot configure 115200 baud, 8N1"
    return
  }

  if ! exec {fd}<>"$path"; then
    stty -F "$path" "$saved_settings" 2>/dev/null || true
    PROBE_DETAIL="cannot open device (check permissions or stop other SQM software)"
    return
  fi

  printf 'ix\r' >&"$fd"
  IFS= read -r -t 2 -u "$fd" response || true
  exec {fd}>&-
  stty -F "$path" "$saved_settings" 2>/dev/null || true
  response=${response%$'\r'}

  if [[ "$response" =~ ^[iI],[[:space:]]*0*([0-9]+),[[:space:]]*0*([0-9]+),[[:space:]]*0*([0-9]+),[[:space:]]*0*([0-9]+)[[:space:]]*$ ]]; then
    protocol=$((10#${BASH_REMATCH[1]}))
    model=$((10#${BASH_REMATCH[2]}))
    feature=$((10#${BASH_REMATCH[3]}))
    serial_number=$((10#${BASH_REMATCH[4]}))
    PROBE_VERIFIED=true
    PROBE_DETAIL="Unihedron SQM model ${model}, serial ${serial_number}, protocol ${protocol}, feature ${feature}"
  elif [[ -n "$response" ]]; then
    PROBE_DETAIL="unexpected response: ${response}"
  else
    PROBE_DETAIL="no reply within 2 seconds"
  fi
}

render_override() {
  local device=$1
  local group_id=$2
  cat <<EOF
${GENERATED_MARKER}; rerun the script to update it.
services:
  sqm:
    devices:
      - '${device}:/dev/sqm'
    group_add:
      - '${group_id}'
    environment:
      SQM_SERIAL_DEVICE: /dev/sqm
      SQM_BAUD_RATE: '115200'
EOF
}

while (($#)); do
  case "$1" in
    --device)
      (($# >= 2)) || fail "--device requires a path"
      REQUESTED_DEVICE=$2
      shift 2
      ;;
    --output)
      (($# >= 2)) || fail "--output requires a file"
      OUTPUT_FILE=$2
      shift 2
      ;;
    --compose-file)
      (($# >= 2)) || fail "--compose-file requires a file"
      COMPOSE_FILE=$2
      shift 2
      ;;
    --skip-probe)
      SKIP_PROBE=true
      shift
      ;;
    --force)
      FORCE=true
      shift
      ;;
    --yes)
      ASSUME_YES=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

[[ "$(uname -s)" == "Linux" ]] || fail "this wizard requires a native Linux Docker host"
[[ -f "$COMPOSE_FILE" ]] || fail "base Compose file not found: $COMPOSE_FILE"
command -v stty >/dev/null 2>&1 || fail "required command not found: stty"
command -v stat >/dev/null 2>&1 || fail "required command not found: stat"
command -v readlink >/dev/null 2>&1 || fail "required command not found: readlink"

declare -a CANDIDATES=()
declare -A SEEN_TARGETS=()

if [[ -n "$REQUESTED_DEVICE" ]]; then
  validate_device "$REQUESTED_DEVICE" || fail "$REQUESTED_DEVICE is not a usable character device below /dev"
  CANDIDATES+=("$REQUESTED_DEVICE")
else
  shopt -s nullglob
  for candidate in /dev/serial/by-id/* /dev/ttyUSB* /dev/ttyACM*; do
    validate_device "$candidate" || continue
    target=$(readlink -f -- "$candidate" 2>/dev/null || printf '%s' "$candidate")
    [[ -n "${SEEN_TARGETS[$target]:-}" ]] && continue
    SEEN_TARGETS[$target]=1
    CANDIDATES+=("$candidate")
  done
  shopt -u nullglob
fi

((${#CANDIDATES[@]})) || {
  printf '%s\n' \
    "No USB serial devices were found." \
    "Plug in the meter, confirm a path appears under /dev/serial/by-id," \
    "and run this script again." >&2
  exit 1
}

declare -a VERIFIED=()
declare -a DETAILS=()
verified_count=0
verified_index=-1

printf 'USB serial candidates:\n'
for index in "${!CANDIDATES[@]}"; do
  candidate=${CANDIDATES[$index]}
  probe_device "$candidate"
  VERIFIED[$index]=$PROBE_VERIFIED
  DETAILS[$index]=$PROBE_DETAIL
  if [[ "$PROBE_VERIFIED" == true ]]; then
    marker="verified SQM"
    ((verified_count += 1))
    verified_index=$index
  else
    marker="not verified"
  fi
  printf '  %d. ' "$((index + 1))"
  describe_device "$candidate"
  printf '\n     %s: %s\n' "$marker" "$PROBE_DETAIL"
done

selected_index=-1
if ((verified_count == 1)); then
  if [[ "$ASSUME_YES" == true ]] || ask_yes_no "Use ${CANDIDATES[$verified_index]}?" yes; then
    selected_index=$verified_index
  else
    fail "setup cancelled"
  fi
elif [[ "$ASSUME_YES" == true ]]; then
  if ((${#CANDIDATES[@]} == 1)); then
    selected_index=0
  else
    fail "--yes requires exactly one candidate or one verified SQM"
  fi
else
  printf '\n'
  while ((selected_index < 0)); do
    read -r -p "Select a device [1-${#CANDIDATES[@]}], or q to quit: " answer
    [[ "${answer,,}" == "q" ]] && fail "setup cancelled"
    if [[ "$answer" =~ ^[0-9]+$ ]] && ((answer >= 1 && answer <= ${#CANDIDATES[@]})); then
      candidate_index=$((answer - 1))
      if [[ "${VERIFIED[$candidate_index]}" == true ]] || ask_yes_no "This device was not verified as an SQM. Continue anyway?" no; then
        selected_index=$candidate_index
      fi
    fi
  done
fi

selected_device=${CANDIDATES[$selected_index]}
group_id=$(stat -c '%g' -- "$selected_device") || fail "could not determine the device group"

if [[ -e "$OUTPUT_FILE" && "$FORCE" != true ]]; then
  first_line=$(head -n1 -- "$OUTPUT_FILE" 2>/dev/null || true)
  if [[ "$first_line" != "$GENERATED_MARKER"* ]]; then
    fail "$OUTPUT_FILE already exists and was not generated by this script; use --output compose.usb.yaml instead"
  fi
  if [[ "$ASSUME_YES" != true ]] && ! ask_yes_no "Replace generated $OUTPUT_FILE?" yes; then
    fail "setup cancelled"
  fi
fi

output_directory=$(dirname -- "$OUTPUT_FILE")
mkdir -p -- "$output_directory"
TEMPORARY_FILE=$(mktemp "${output_directory}/.$(basename -- "$OUTPUT_FILE").XXXXXX")
render_override "$selected_device" "$group_id" >"$TEMPORARY_FILE"
chmod 0644 "$TEMPORARY_FILE"
mv -f -- "$TEMPORARY_FILE" "$OUTPUT_FILE"
TEMPORARY_FILE=""

validation_message="Docker CLI not found; skipped Compose validation"
if command -v docker >/dev/null 2>&1; then
  if docker compose -f "$COMPOSE_FILE" -f "$OUTPUT_FILE" config --quiet; then
    validation_message="Compose configuration validated"
  else
    fail "wrote $OUTPUT_FILE, but Docker Compose rejected it"
  fi
fi

printf '\n'
printf 'Wrote USB mapping: %s\n' "$OUTPUT_FILE"
printf 'Host device:       %s\n' "$selected_device"
printf 'Container device:  /dev/sqm\n'
printf 'Device group ID:   %s\n' "$group_id"
printf '%s\n' "$validation_message"
if [[ "$(basename -- "$OUTPUT_FILE")" == "compose.override.yaml" ]]; then
  printf 'Next: docker compose up -d\n'
else
  printf 'Next: docker compose -f %s -f %s up -d\n' "$COMPOSE_FILE" "$OUTPUT_FILE"
fi
printf '%s\n' \
  "Then open the Meter page, choose USB / serial, and use" \
  "Find mapped USB meters."
