from __future__ import annotations

import subprocess
from pathlib import Path

from fake_serial import FakeSerialSQM


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "setup-usb.sh"


def test_shell_wizard_probes_meter_and_writes_override(tmp_path: Path):
    output = tmp_path / "compose.override.yaml"
    with FakeSerialSQM() as meter:
        completed = subprocess.run(
            [
                "bash",
                str(SCRIPT),
                "--device",
                meter.path,
                "--output",
                str(output),
                "--compose-file",
                str(ROOT / "compose.yaml"),
                "--yes",
            ],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
        )

    assert completed.returncode == 0, completed.stderr
    assert "verified SQM" in completed.stdout
    assert meter.commands == [b"ix"]
    generated = output.read_text(encoding="utf-8")
    assert generated.startswith("# Generated by setup-usb.sh")
    assert f"'{meter.path}:/dev/sqm'" in generated
    assert "SQM_SERIAL_DEVICE: /dev/sqm" in generated


def test_shell_wizard_preserves_unowned_override(tmp_path: Path):
    output = tmp_path / "compose.override.yaml"
    output.write_text("services:\n  something-else: {}\n", encoding="utf-8")
    with FakeSerialSQM() as meter:
        completed = subprocess.run(
            [
                "bash",
                str(SCRIPT),
                "--device",
                meter.path,
                "--output",
                str(output),
                "--compose-file",
                str(ROOT / "compose.yaml"),
                "--skip-probe",
                "--yes",
            ],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
        )

    assert completed.returncode == 2
    assert "was not generated by this script" in completed.stderr
    assert output.read_text(encoding="utf-8") == "services:\n  something-else: {}\n"
